# Generated by Django 3.1.4 on 2020-12-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
